defaultDashboards:
  defaultTimezone: Europe/Berlin

vmsingle:
  ingress:
  enabled: true
  ingressClassName: cilium
  annotations:
      cert-manager.io/cluster-issuer: cloudflare-letsencrypt-${environment}
      ingress.cilium.io/loadbalancer-mode: shared
  hosts: ${vmsingle_domains}
  tls:
    - secretName: vmsingle-tls
      hosts: ${vmsingle_domains}

alertmanager:
  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-letsencrypt-${environment}
      ingress.cilium.io/loadbalancer-mode: shared
    hosts: ${alertmanager_domains}
    tls:
    - secretName: alertmanager-tls
      hosts: ${alertmanager_domains}

vmalert:
  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-letsencrypt-${environment}
      ingress.cilium.io/loadbalancer-mode: shared
    hosts: ${vmalert_domains}
    tls:
    - secretName: vmalert-tls
      hosts: ${vmalert_domains}

vmagent:
  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-letsencrypt-${environment}
      ingress.cilium.io/loadbalancer-mode: shared
    hosts: ${vmagent_domains}
    tls:
    - secretName: vmagent-tls
      hosts: ${vmagent_domains}

grafana:
  # grafana.ini:
  #   auth:
  #     signout_redirect_url: "https://auth.steled.org/application/o/grafana/end-session/"
  #     oauth_auto_login: true
  #   auth.generic_oauth:
  #     name: authentik
  #     enabled: true
  #     client_id: "${grafana_client_id}"
  #     client_secret: "${grafana_client_secret}"
  #     scopes: "openid profile email"
  #     auth_url: "https://auth.steled.org/application/o/authorize/"
  #     token_url: "https://auth.steled.org/application/o/token/"
  #     api_url: "https://auth.steled.org/application/o/userinfo/"
  #     # Optionally map user groups to Grafana roles
  #     role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'

  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-letsencrypt-${environment}
      ingress.cilium.io/loadbalancer-mode: shared
    hosts: ${grafana_domains}
    tls:
      - secretName: grafana-tls
        hosts: ${grafana_domains}

  persistence:
    enabled: true
    storageClassName: longhorn

  admin:
    existingSecret: victoriametrics-secret
    userKey: grafana_admin-user
    passwordKey: grafana_admin-password

kubeProxy:
  enabled: true
