name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

env:
  TF_VER: 1.2.8

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: $TF_VER

    - name: Terraform Format
      id: fmt
      run: terraform fmt -recursive
      continue-on-error: true

    - uses: EndBug/add-and-commit@v9

#    - name: Terraform Init
#      id: init
#      run: terraform init

    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\``
